using VRage.Game;

namespace Equinox.EnergyWeapons.Definition.Weapon
{
    public abstract class EnergyWeaponDefinition
    {
        /// <summary>
        /// The definition's ID
        /// </summary>
        public MyDefinitionId Id { get; }

        protected EnergyWeaponDefinition(MyDefinitionId id)
        {
            Id = id;
        }

        /// <summary>
        /// Should ammo be autogenerated for this weapon.
        /// </summary>
        public abstract bool GenerateAmmo { get; }
    }
}
